sudo: required
env: 
language: python
python:
- '3.6'
cache: pip
before_install:
- sudo apt-get update
install:
- pip install -r requirements.txt
- pip install pytest pytest-cov
- pip install coveralls
- pip install mypy
script:
- py.test --doctest-modules --cov=entity_embeddings/
after_success:
- coveralls
deploy:
  provider: pypi
  user: bresan
  distributions: sdist bdist_wheel
  on:
    branch: master
  skip_existing: true
  password:
    secure: Yj8ZfX79A/nkkGQdSNhCC2XTCEWVLdSArqzyMas5WAr2LeQ+HR8pTqA/4cIvmOhTUSu9XwpLLvyqDZI4sjrm3FrOpycanjqEwCTbowVEANq3CMvV8L7J4/ut5Of7jK7ncjsD0RIJHwuaOy4HF/AxoWSs1g9sEN1wcFqdygWAApPd8My+oeIcOFZZ5wAWontO5c3df79SzCabDF4sqAzoukb/7F6AUamFNMVt6CqIhXL/IlL6O9sJiv4nJJvo5I/LEWy8Ps8q6a0QtPItqgLSmt94k5y7qRkRQ4y+PB4P6A3p1G9YG2Dw2GEYhQ+kOk2JDHrq30r65nZAlzob05mpgT6FjAvleFrGOz72MEybaFLtOwfpj0gvezaojNvZUQdy1PcSJEw/jXlyQD5W1/vcJXeCR/rpzT5A2OndcNgBgHSqsr1/4gZwdRmxWYyegidatqtlnvSUIVQ4L16lkGuq2x9gPiLqwYSRq91SRCINKdu1N1oheVLmQ9UtgZGjdlC2EvA7WH9SAs/L4clAqd4ufwP2/UvmPBUG+KlMQo2vLAXX8IWyhyC8Ud15yriSLgO9hHyg7mEdwcL7G1LLBFiknfZdKLGwX8KaQHrCb2zUyGAZE05tRNKlM0vS1wkkEl917XdGQMXXuMCALcA18UWnq038UOaH3hINtVd//Vk0Z8w=
