sudo: required
env: 
language: python
python:
- '3.6'
cache: pip
before_install:
- sudo apt-get update
install:
- pip install -r requirements.txt
- pip install pytest pytest-cov
- pip install coveralls
script: py.test --doctest-modules --cov
after_success:
- coveralls
deploy:
  provider: pypi
  user: bresan
  distributions: sdist bdist_wheel
  on:
    branch: master
  skip_existing: true
  password:
    secure: moZrJsnEyhGb/EAx547FZkt/sUnbn5SrIFfJCCaZuBC+riItk0m9NjCnaLObUthXvEOvkwIOMkC85BGG+JUwraIVTEqI9POmjDSFR0R4veeph8Voy8A8gVsKZ1JU5ccXIl3BBCVpa00ttG66sYAlBdgeRYcrrfxUUvaKttiuQzNoAjHpIGmMV0hFCnVJImbGBd5BS19xfdgZEktxRM6v0ZeKJmJDBTgoXKQfGz9C6rQNJ2tG6LrS5VRxw/enqaH3+Quz5iptKE0zRnJEIe2iAlHuVVqP+TkTBCqqNuB4kRWPTlPD2T1zFGsLI9XiOdiQ1y+6xdHk5uiJ9a5RgV4nRNBtx3x/kDajb7I9GHfd+d9Pij3RC5kDZ6eXDFX1MnEX6qXcR/VluMXYU9Ug7e5uump1MFHkzrBXLACAhb8EKxQqryNgLCmVy0NX+90QNLwtHYr/5yrUVcxL3nJuDd1iSb+3gB5jrmpxmLPeIxd7JnxY5mccvSGKJsF5tmOfO7mIpjV9l9R9Hd8t5M6xz1Y+ozMSJP3Hb/o1WvOVV8hopqOP9B+FtqGnBb08gMyaQrEOGP4M+utMvz6y4udbAM0cEdsvoyyBlq0X6jGKX5fbXRo3wmxrr5TofUTQecAlY2nY0al/VWfQsM/7modi6oyL0DVQy+rtB3K4VcSus8fS8DY=
